function run_batch(batch_structure)
% Runs a batch using a parfor loop if there is more than 1 job in the batch

% Cycle through the trials
job_structure = batch_structure.job;

if (numel(job_structure)>1)
    parfor i=1:numel(job_structure)
        
        simulation_driver( ...
            'model_json_file_string', ...
                job_structure{i}.model_file_string, ...
            'simulation_protocol_file_string', ...
                job_structure{i}.protocol_file_string, ...
            'options_json_file_string', ...
                job_structure{i}.options_file_string, ...
            'output_file_string', ...
                job_structure{i}.results_file_string);
            
            
    end
else
    simulation_driver( ...
        'model_json_file_string', ...
            job_structure{1}.model_file_string, ...
        'simulation_protocol_file_string', ...
            job_structure{1}.protocol_file_string, ...
        'options_json_file_string', ...
            job_structure{1}.options_file_string, ...
        'output_file_string', ...
            job_structure{1}.results_file_string);
end    
