function generate_protocol

% Variables
protocol_file_string = 'ramp_3_protocol.txt';

% Generate the protocol
generate_triangle_protocol( ...
    'output_file_string', protocol_file_string, ...
    'pre_first_triangle_s',0.5, ...
    'triangle_rise_time_s',0.1, ...
    'plateau_s',0.2, ...
    'pre_ktr_s',0.5, ...
    'activating_pCa', 4.5);