function check_new_force(obj, new_length, time_step)
% Function calculates the force for a given length

% Calculate the change in length
delta_hs_length = new_length - obj.hs_length;

% Calculate the change in myosin force
delta_m_force = (1 - obj.parameters.prop_fibrosis) * ...
                    obj.parameters.prop_myofilaments * ...
                    obj.parameters.cb_number_density * ...
                    obj.f_bound * ...
                    obj.parameters.compliance_factor * delta_hs_length * ...
                    1e-9 * obj.parameters.k_cb;

% And the change in c force
delta_c_force = 0;

% And the change in passive force
delta_int_pas_force = ...
    obj.return_intracellular_passive_force(new_length) - ...
        obj.int_passive_force;
    
delta_ext_pas_force = ...
    obj.return_extracellular_passive_force(new_length) - ...
        obj.ext_passive_force;

% And the viscous force
delta_viscous_force = (1- obj.parameters.prop_fibrosis) * ...
                        (obj.parameters.prop_myofilaments) * ...
                obj.parameters.viscosity * delta_hs_length / time_step;

% Add them up
obj.check_force = obj.hs_force + ...
                    delta_m_force + delta_c_force + ...
                    delta_int_pas_force + delta_ext_pas_force + ...
                    delta_viscous_force;
