function check_new_force(obj, new_length, time_step)
% Function calculates the force for a given length

% Calculate the change in length
delta_hs_length = new_length - obj.hs_length;

cb_force = obj.cb_force + ...
                (1- obj.parameters.prop_fibrosis) * ...
                        obj.parameters.prop_myofilaments * ...
                obj.parameters.cb_number_density * ...
                    obj.f_bound * ...
                    obj.parameters.compliance_factor * delta_hs_length * ...
                    1e-9 * obj.parameters.k_cb;

int_passive_force = obj.return_intracellular_passive_force(new_length);

ext_passive_force = obj.return_extracellular_passive_force(new_length);

viscous_force = (1- obj.parameters.prop_fibrosis) * ...
                        (obj.parameters.prop_myofilaments) * ...
                obj.parameters.viscosity * delta_hs_length / time_step;

% Add them up
obj.check_force = cb_force + int_passive_force + ext_passive_force + ...
                    viscous_force;