function pf = return_extracellular_passive_force(obj,hsl)
% Function returns passive force

switch (obj.parameters.ext_passive_force_mode)
    case 'linear'
        pf = obj.parameters.prop_fibrosis * ...
                obj.parameters.ext_passive_k_linear * ...
                    (hsl - obj.parameters.ext_passive_hsl_slack);
    case 'exponential'
        if (hsl> obj.parameters.ext_passive_hsl_slack)
            pf = obj.parameters.prop_fibrosis * ...
                    obj.parameters.ext_passive_sigma * ...
                        (exp((hsl - obj.parameters.ext_passive_hsl_slack)/ ...
                            obj.parameters.ext_passive_L)-1);
        else
            pf = obj.parameters.prop_fibrosis * ...
                    -obj.parameters.ext_passive_sigma * ...
                        (exp(-(hsl - obj.parameters.ext_passive_hsl_slack)/ ...
                            obj.parameters.ext_passive_L)-1);
        end
    otherwise
        error('Passive force mode not defined');
end
        
