function pf = return_intracellular_passive_force(obj,hsl)
% Function returns passive force

switch (obj.parameters.int_passive_force_mode)
    case 'linear'
        pf = (1 - obj.parameters.prop_fibrosis) * ...
                obj.parameters.prop_myofilaments * ...
             obj.parameters.int_passive_k_linear * ...
                (hsl - obj.parameters.int_passive_hsl_slack);
    case 'exponential'
        if (hsl> obj.parameters.int_passive_hsl_slack)
            pf = (1 - obj.parameters.prop_fibrosis) * ...
                    obj.parameters.prop_myofilaments * ...
                obj.parameters.int_passive_sigma * ...
                    (exp((hsl - obj.parameters.int_passive_hsl_slack)/ ...
                        obj.parameters.int_passive_L)-1);
        else
            pf = (1 - obj.parameters.prop_fibrosis) * ...
                    obj.parameters.prop_myofilaments * ...
                -obj.parameters.int_passive_sigma * ...
                    (exp(-(hsl - obj.parameters.int_passive_hsl_slack)/ ...
                        obj.parameters.int_passive_L)-1);
        end
    otherwise
        error('Passive force mode not defined');
end
        
        
