function update_forces(obj, time_step, delta_hsl)

if (startsWith(obj.kinetic_scheme, '2state'))
    bin_pops = obj.myofilaments.y(1+(1:obj.myofilaments.no_of_x_bins));
    obj.cb_force = ...
            obj.parameters.cb_number_density *  ...
                obj.parameters.k_cb * 1e-9 * ...
                sum((obj.myofilaments.x + obj.parameters.x_ps) .* ...
                    bin_pops');
end

if (startsWith(obj.kinetic_scheme, '3state_with_SRX'))
    bin_pops = obj.myofilaments.y(2+(1:obj.myofilaments.no_of_x_bins));
    obj.cb_force = ...
            obj.parameters.cb_number_density *  ...
                obj.parameters.k_cb * 1e-9 * ...
                sum((obj.myofilaments.x + obj.parameters.x_ps) .* ...
                    bin_pops');
end

if (startsWith(obj.kinetic_scheme, '4state_with_SRX'))
    M3_indices = 2+(1:obj.myofilaments.no_of_x_bins);
    M4_indices = (2+obj.myofilaments.no_of_x_bins) + ...
        (1:obj.myofilaments.no_of_x_bins);

    M3 = obj.myofilaments.y(M3_indices);
    M4 = obj.myofilaments.y(M4_indices);

    obj.cb_force = ...
        obj.parameters.cb_number_density * ...
            obj.parameters.k_cb * 1e-9 * ...
            (sum(obj.myofilaments.x .* M3') + ...
                sum((obj.myofilaments.x + obj.parameters.x_ps) .* M4'));
end

obj.intracellular_passive_force = ...
    obj.return_intracellular_passive_force(obj.hs_length);

obj.extracellular_passive_force = ...
    obj.return_extracellular_passive_force(obj.hs_length);

obj.viscous_force = obj.parameters.viscosity * delta_hsl / time_step;

obj.hs_force = obj.cb_force + obj.intracellular_passive_force + ...
    obj.viscous_force + obj.extracellular_passive_force;